context:
  name: cherab-imas
  version: "0.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/cherab/imas/archive/v${{ version }}.tar.gz
  sha256: 49c940f9eb126b6b8696fcd1e6530ca17edecdccd9a36c60f00d9c19bc45e7bb
  patches:
    - fix_timeout.patch

build:
  skip:
    - win
  script:
    content: ${{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
  number: 0

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - hatch-cython >=0.6.0rc0
        - hatch-vcs
        - cherab
        - if: osx
          then:
            - llvm-openmp
  host:
    - python
    - pip
    - hatch-cython >=0.6.0rc0
    - hatch-vcs
    - cherab
    - if: osx
      then:
        - llvm-openmp
  run:
    - python
    - imas-python
    - pooch
    - rich

tests:
  - python:
      imports:
        - cherab.imas
        - cherab.imas.datasets
        - cherab.imas.ggd
        - cherab.imas.ids
        - cherab.imas.math
        - cherab.imas.plasma
        - cherab.imas.wall
      pip_check: false
  - script:
      - pytest tests/ -v
    files:
      source:
        - tests/
    requirements:
      run:
        - pytest
        - pytest-cov

about:
  homepage: https://github.com/cherab/imas
  summary: Cherab add-on module for IMAS (Integrated Modelling & Analysis Suite)
  description: |
    This module enables the creation of cherab's functional objects (e.g. plasma, observers, meshes, etc.) from IMAS IDS (Interface Data Structures).
  license: EUPL-1.1
  license_file: LICENCE.txt
  documentation: https://cherab.github.io/imas/
  repository: https://github.com/cherab/imas

extra:
  recipe-maintainers:
    - munechika-koyo
